### ISSUE TITLE
Fetch the "main" branch of the First Responder Kit (rather than "master")

### ISSUE THREAD

**Issue by BrentOzar** [dzsquared/sqlops-firstresponderkit#27]
I renamed the branches this morning, so doing a pull request to switch the source. I have no idea if this is all the changes you need, but wanted to help get it started.

**Comment by dzsquared** [comment]
**Thank you for raising an issue for the Azure Data Studio extension for the First Responder Kit!**

This isn't my full time job, but I hope to get back to you soon. I really appreciate feedback on issues and new feature requests!
        
If your question involves the First Responder Kit directly, you may find help in the [#FirstResponderKit Slack Channel](https://sqlcommunity.slack.com/messages/firstresponderkit/).

**Comment by dzsquared** [comment]
Thank you!  Will be able to get the change released within a few days.

**Comment by dzsquared** [comment]
As I ran through a variety of completely unautomated tests before publishing a release with this change - I noticed the latest FRK release tag in GitHub (20200704) doesn't match the current code in FRK (20200703).  
I never discussed the use of the release tag to determine the current version in comparison to the @VersionDate variable with you, just checking if I should rework this functionality in the future or if its a 1-off incident due to the quick fix.

**Comment by BrentOzar** [comment]
Ah, it was a one off issue due to the emergency release. I can do a new release with the tag and date matching if you need though.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by dzsquared** [comment]
I don't think the release @versiondate change warrants another release, I don't have the utilization on the "check version" feature to back up that time investment. Just wanted to check that it was a one-off. Thanks!
(new release with correct branch name in the morning)

**Comment by BrentOzar** [comment]
Just checking in - had someone report the problem over on the blog, making sure you didn't forget about this one. Thanks!

**Comment by dzsquared** [comment]
Well, it took an embarrassing amount of time to get the fixed release out.  It should be hitting the marketplace(s) soon - v0.6.0
